### ISSUE TITLE
Would it be possible to make this an official HA integration?

### ISSUE THREAD

**Issue by ghost** [AcidSleeper/Philips-Airpurifier#3]
Hi! Thanks for writing this. Would it be possible to make this an official HA integration or atleast an HACS integration. So more people can enjoy this? https://developers.home-assistant.io/
(Just bought an Philips AC3829 because i'm so damn allergic to dust)
Would be great!

**Comment by AcidSleeper** [comment]
Hey there.
At this moment I have no plan of this. 
At Kraineffs integration in HACS (now removed) there was a Numbers of issues with different AirPurifiers. 
I have not the competense to address all those issues. 

For me and my Philips Ac3259/10 this integration works. 
Im not without competense and have adressed a few and will try to have this alive as long as possible.

**Comment by ghost** [comment]
Okay. Woops sorry for the double post.

**Comment by AcidSleeper** [comment]
No problem.

But not HACS or Integration at this point.
